server:
  port: 8083
spring:
  application:
    name: presentation-service
  cloud:
    config:
      uri: http://localhost:8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/