spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohamedbahrini/config
          clone-on-start: true
server:
  port: 8081
security:
  user:
    name: root
    password: s3cr3t